# https://taskfile.dev

version: '3'
tasks:
  kind:
    cmds:
      - kind create cluster --config kind.yaml
  eks:
    cmds:
      - eksctl create cluster -f eksctl.yaml
  base:
    cmds:
      - kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.1.0" | kubectl apply -f -
      - istioctl install --set profile=ambient --skip-confirmation
      - kubectl label namespace default istio.io/dataplane-mode=ambient
      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/prometheus.yaml --wait
      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/kiali.yaml --wait
      - kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.2.yaml --wait
  update-kind:
    cmds:
      - kubectl apply -k manifests/kind --wait
  update-eks:
    cmds:
      - kubectl apply -k manifests/eks --wait
  destroy-kind:
    cmds:
      - kind delete cluster --config kind.yaml
  destroy-eks:
    cmds:
      - eksctl delete cluster -f eksctl.yaml --disable-nodegroup-eviction
