# https://taskfile.dev

vars:
  TAG:
    sh: curl -s https://storage.googleapis.com/istio-build/dev/latest
version: '3'
tasks:
  istioctl:
    cmds:
      - wget https://storage.googleapis.com/istio-build/dev/{{.TAG}}/istioctl-{{.TAG}}-osx.tar.gz
      - tar -xvf istioctl-{{.TAG}}-osx.tar.gz
      - rm istioctl-{{.TAG}}-osx.tar.gz
      - chmod +x istioctl
  setup-kind:
    cmds:
      - kind create cluster --config kind.yaml
  setup-eks:
    cmds:
      - eksctl create cluster -f eksctl.yaml
  base:
    cmds:
      - kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.1.0" | kubectl apply -f -
      - ./istioctl install --set profile=ambient --set tag={{.TAG}} --skip-confirmation
      - kubectl label namespace default istio.io/dataplane-mode=ambient
      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/prometheus.yaml --wait
      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/kiali.yaml --wait
      - kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.2.yaml --wait
  update:
    cmds:
      - kubectl apply -k manifests/ --wait
  destroy-kind:
    cmds:
      - kind delete cluster --config kind.yaml
  destroy-eks:
    cmds:
      - eksctl delete cluster -f eksctl.yaml --disable-nodegroup-eviction
