# https://taskfile.dev

version: '3'
tasks:
  kind:
    cmds:
      - kind create cluster --config kind.yaml
      - kubectl config use-context kind-istio-ambient-cloudnativepg
  setup:
    cmds:
      - kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.1.0" | kubectl apply -f -; }
      - istioctl install --set profile=ambient --skip-confirmation
      - kubectl label namespace default istio.io/dataplane-mode=ambient
      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/prometheus.yaml
      - kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/kiali.yaml
      - kubectl apply --server-side -f https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.2.yaml --wait
  apply:
    cmds:
      - kubectl apply -k manifests/test-cluster --wait
      - kubectl apply -k manifests/test-client-psql --wait
      - kubectl apply -k manifests/test-client-goose --wait
      - kubectl exec deploy/goose -- go install github.com/pressly/goose/v3/cmd/goose@latest
