apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: k8s-api-ext
spec:
  hosts:
    - kubernetes.default.svc.cluster.local
  addresses:
    - 10.100.0.1
  endpoints:
    - address: 10.100.0.1
  location: MESH_EXTERNAL
  resolution: STATIC
  ports:
    - number: 443
      name: https-k8s
      protocol: HTTPS
