apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    labels:
      app: postgres
      version: "1"
  storage:
    storageClass: standard
    size: 1Gi
