kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapi-client
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - 'list'
