apiVersion: apps/v1
kind: Deployment
metadata:
  name: goose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goose
  template:
    metadata:
      labels:
        app: goose
    spec:
      containers:
        - name: goose
          image: golang:bookworm
          command: ["sleep"]
          args: ["infinity"]
          livenessProbe:
            exec:
              command:
                - go
                - version
